# Judge0 configuration file
# See https://github.com/judge0/judge0/blob/master/judge0.conf for full list of options.

REDIS_PASSWORD=judge0_redis_password
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_db_password
POSTGRES_DB=judge0
POSTGRES_HOST=db

REDIS_HOST=redis

# Security
# AUTH_CALLBACK_TOKEN=secret_token
# ENABLE_BETA_PROGRAM=false

# Limits
# MAX_CPU_TIME=10
# MAX_MEMORY=128000
